### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by trvinh** [giangnguyen0709/fCAT#1]
- [x] improve DOC (link to download e.g. Hannah's BUSCO set; clearer description for options and give specific example of run command; detailed explanation in MAN files, e.g. `#' @param scoreMode the mode determines the method to assess the founded ortholog` should be `#' @param scoreMode the mode determines the method for assessing completeness type of the founded orthologs. Choices: 1, 2, 3 or "busco"`; add examples for each function)
- [x] compare your DESCRIPTION file with the one of PhyloProfile and improve it
- [x] check coding style
- [ ] detailed explanation about the functions in R folder (how they link to each other)
- [x] replace h1s by fdog
- [x] option to input blast_dir, weight_dir, old phyloprofile files independently (not necessary always present in "root" dir)
- [x] option to specify output dir (by default can be write in "root" folder)
- [x] change option "root" by other name
- [x] rename `check_dir` to e.g. `query_taxon`
- [x] validate input before calculating

**Comment by trvinh** [comment]
potential improvements

- [ ] instead of calculating annotations for each core group, one should directly use annotation in weight_dir/*.json 
- [ ] cutoff calculation should run in parallel
- [ ] run h1s for **n** core groups in parallel, each h1s job needs only 1 cpu
- [x] run h1s for all core groups with `--fasoff` option and than run hamstrFAS on merged extended.fa file
